name: Continuous Integration
on: [push]
jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Clean Build
        run: ./gradlew clean build
